import { byDateDesc, computeDueItems } from '@/domain/derive';
import type { Entry, Intent } from '@/domain/types';
import { pick, type Lang } from '@/i18n';
import { formatDate, formatEuro } from '@/lib/format';
import type { Fixtures } from './index';

export const CHAT_OBJEKT_ID = 'rb-01';

export const chatFallback = (lang: Lang): string =>
  pick(lang)(
    'Dazu finde ich nichts in den Dokumenten dieses Objekts. Probier eine der vorgeschlagenen Fragen.',
    'I cannot find anything about that in the documents of this property. Try one of the suggested questions.',
  );

/**
 * Prepared questions and answers for "Frag dein Scheckheft". The answers are scripted, but
 * their dates, amounts and sources are taken from the fixtures so they match what the
 * documents show. Nothing is generated by a model.
 */
export function buildIntents(fx: Fixtures, added: Entry[], lang: Lang): Intent[] {
  const L = pick(lang);
  const objekt = fx.objekte.find((o) => o.id === CHAT_OBJEKT_ID)!;
  const anlagen = fx.anlagen.filter((a) => a.objektId === objekt.id);
  const rules = fx.rules.filter((r) => anlagen.some((a) => a.id === r.anlageId));
  const entries = [...fx.entries, ...added]
    .filter((e) => e.objektId === objekt.id)
    .sort(byDateDesc);
  const items = computeDueItems(entries, rules, anlagen, [], fx.today);
  const docsOf = (e: Entry | undefined, typ?: string) =>
    (e?.dokumente ?? []).filter((d) => !typ || d.typ === typ).map((d) => d.id);

  const heizung = entries.find((e) => e.ruleId === `${objekt.id}-r-heizung`);
  const heizungDue = items.find((i) => i.rule.id === `${objekt.id}-r-heizung`);
  const overdue = items.filter((i) => i.status === 'overdue');
  const yearAgo = `${Number(fx.today.slice(0, 4)) - 1}${fx.today.slice(4)}`;
  const lastYear = entries.filter((e) => e.date >= yearAgo);
  const lastYearCost = formatEuro(lastYear.reduce((sum, e) => sum + e.costCents, 0));
  const elektro = entries.find((e) => e.ruleId === `${objekt.id}-r-elektro`);
  const garantie = entries.find((e) => e.dokumente.some((d) => d.typ === 'garantie'));
  const street = objekt.address.street;

  return [
    {
      id: 'letzte-heizungswartung',
      question: L('Wann war die letzte Heizungswartung?', 'When was the last heating service?'),
      keywords: L(
        ['heizungswartung', 'heizung', 'wartung', 'letzte'],
        ['heating', 'service', 'last', 'boiler'],
      ),
      answer: heizung
        ? L(
            `Die letzte Heizungswartung in der ${street} war am ${formatDate(heizung.date)} durch ${heizung.betriebName} (${formatEuro(heizung.costCents)}).`,
            `The last heating service at ${street} was on ${formatDate(heizung.date)} by ${heizung.betriebName} (${formatEuro(heizung.costCents)}).`,
          ) +
          (heizungDue
            ? L(
                ` Der nächste Termin wird für den ${formatDate(heizungDue.dueDate)} empfohlen.`,
                ` The next date is recommended for ${formatDate(heizungDue.dueDate)}.`,
              )
            : '')
        : L(
            'Für dieses Objekt ist noch keine Heizungswartung dokumentiert.',
            'No heating service has been documented for this property yet.',
          ),
      sourceDokumentIds: docsOf(heizung),
    },
    {
      id: 'ueberfaellig',
      question: L('Was ist überfällig?', 'What is overdue?'),
      keywords: L(
        ['ueberfaellig', 'faellig', 'offen', 'versaeumt'],
        ['overdue', 'due', 'missed', 'late'],
      ),
      answer:
        overdue.length > 0
          ? L(
              `Überfällig ist: ${overdue
                .map((i) => `${i.rule.title} (empfohlen zum ${formatDate(i.dueDate)})`)
                .join(', ')}. Die Termine sind Empfehlungen aus den hinterlegten Intervallen.`,
              `Overdue: ${overdue
                .map((i) => `${i.rule.title} (recommended for ${formatDate(i.dueDate)})`)
                .join(', ')}. The dates are recommendations based on the stored intervals.`,
            )
          : L(
              'Nach den hinterlegten Empfehlungen ist in diesem Objekt nichts überfällig.',
              'According to the stored recommendations, nothing is overdue in this property.',
            ),
      sourceDokumentIds: overdue.flatMap((i) => docsOf(i.lastEntry, 'protokoll')),
    },
    {
      id: 'kosten',
      question: L(
        'Was hat die Instandhaltung in den letzten 12 Monaten gekostet?',
        'What did maintenance cost in the last 12 months?',
      ),
      keywords: L(
        ['kosten', 'gekostet', 'ausgaben', 'teuer', 'instandhaltung'],
        ['cost', 'costs', 'spent', 'expensive', 'maintenance'],
      ),
      answer: L(
        `In den letzten 12 Monaten sind ${lastYearCost} für ${lastYear.length} dokumentierte Arbeiten angefallen.`,
        `In the last 12 months, ${lastYearCost} was spent on ${lastYear.length} documented jobs.`,
      ),
      sourceDokumentIds: lastYear.flatMap((e) => docsOf(e, 'rechnung')),
    },
    {
      id: 'elektro',
      question: L('Wer hat die Elektroprüfung gemacht?', 'Who did the electrical inspection?'),
      keywords: L(
        ['elektro', 'elektropruefung', 'strom', 'wer'],
        ['electrical', 'electric', 'inspection', 'who'],
      ),
      answer: elektro
        ? L(
            `Die letzte Prüfung der elektrischen Anlagen hat ${elektro.betriebName} am ${formatDate(elektro.date)} durchgeführt.`,
            `The last electrical installation inspection was carried out by ${elektro.betriebName} on ${formatDate(elektro.date)}.`,
          )
        : L(
            'Für dieses Objekt ist noch keine Elektroprüfung dokumentiert.',
            'No electrical inspection has been documented for this property yet.',
          ),
      sourceDokumentIds: docsOf(elektro, 'protokoll'),
    },
    {
      id: 'garantie',
      question: L(
        'Gibt es Garantieunterlagen zur Heizung?',
        'Are there warranty documents for the heating?',
      ),
      keywords: L(
        ['garantie', 'gewaehrleistung', 'garantieunterlagen'],
        ['warranty', 'guarantee'],
      ),
      answer: garantie
        ? L(
            `Ja. Zur Arbeit „${garantie.title}“ vom ${formatDate(garantie.date)} liegen Garantieunterlagen von ${garantie.betriebName} vor.`,
            `Yes. For the job "${garantie.title}" on ${formatDate(garantie.date)} there are warranty documents from ${garantie.betriebName}.`,
          )
        : L(
            'Für dieses Objekt liegen keine Garantieunterlagen vor.',
            'There are no warranty documents for this property.',
          ),
      sourceDokumentIds: docsOf(garantie, 'garantie'),
    },
  ];
}
